#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${QWEN36_ENV_FILE:-${ROOT_DIR}/config/qwen36.env}"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "env file not found: ${ENV_FILE}" >&2
  exit 1
fi

while IFS='=' read -r key value; do
  [[ -z "${key}" || "${key}" == \#* ]] && continue
  if [[ "${key}" =~ ^[A-Za-z_][A-Za-z0-9_]*$ && -z "${!key+x}" ]]; then
    export "${key}=${value}"
  fi
done <"${ENV_FILE}"

QWEN36_BACKEND_TYPE="${QWEN36_BACKEND_TYPE:-llamacpp}"
QWEN36_LLAMA_SERVER="${QWEN36_LLAMA_SERVER:-/Users/yukimi/.rencrow/runtimes/llama.cpp/b10327/llama-server}"
QWEN36_PYTHON="${QWEN36_PYTHON:-/Users/yukimi/RenCrow/RenCrow_LLM/.venv/bin/python3}"
QWEN36_MODEL="${QWEN36_MODEL:-/Users/yukimi/models/Qwen3.6-27B-Uncensored-Heretic-v2-GGUF/Qwen3.6-27B-uncensored-heretic-v2-Q4_K_M.gguf}"
QWEN36_RUNTIME_CWD="${QWEN36_RUNTIME_CWD:-/Users/yukimi/RenCrow/RenCrow_LLM}"
QWEN36_RENCROW_START_SCRIPT="${QWEN36_RENCROW_START_SCRIPT:-/Users/yukimi/RenCrow/RenCrow_LLM/scripts/start_mlx_vlm_backend.sh}"
QWEN36_DIRECT_START="${QWEN36_DIRECT_START:-0}"
QWEN36_USE_MGMT="${QWEN36_USE_MGMT:-1}"
QWEN36_MGMT_BASE="${QWEN36_MGMT_BASE:-http://127.0.0.1:8079}"
QWEN36_HOST="${QWEN36_HOST:-0.0.0.0}"
QWEN36_BACKEND_PORT="${QWEN36_BACKEND_PORT:-18084}"
QWEN36_BACKEND_BASE="${QWEN36_BACKEND_BASE:-http://127.0.0.1:${QWEN36_BACKEND_PORT}}"
QWEN36_PROXY_BASE="${QWEN36_PROXY_BASE:-http://127.0.0.1:8084}"
QWEN36_LLAMA_CONTEXT_SIZE="${QWEN36_LLAMA_CONTEXT_SIZE:-65536}"
QWEN36_LLAMA_PARALLEL="${QWEN36_LLAMA_PARALLEL:-1}"
QWEN36_LLAMA_GPU_LAYERS="${QWEN36_LLAMA_GPU_LAYERS:-999}"
QWEN36_LLAMA_FLASH_ATTN="${QWEN36_LLAMA_FLASH_ATTN:-auto}"
QWEN36_LLAMA_CACHE_TYPE_K="${QWEN36_LLAMA_CACHE_TYPE_K:-q8_0}"
QWEN36_LLAMA_CACHE_TYPE_V="${QWEN36_LLAMA_CACHE_TYPE_V:-q8_0}"
QWEN36_LLAMA_CACHE_RAM_MIB="${QWEN36_LLAMA_CACHE_RAM_MIB:-8192}"
QWEN36_LLAMA_CHECKPOINT_MIN_STEP="${QWEN36_LLAMA_CHECKPOINT_MIN_STEP:-256}"
QWEN36_LLAMA_CTX_CHECKPOINTS="${QWEN36_LLAMA_CTX_CHECKPOINTS:-32}"
QWEN36_LLAMA_ALIASES="${QWEN36_LLAMA_ALIASES:-Wild64K,Wild}"
QWEN36_MAX_KV_SIZE="${QWEN36_MAX_KV_SIZE-}"
QWEN36_KV_BITS="${QWEN36_KV_BITS-}"
QWEN36_KV_QUANT_SCHEME="${QWEN36_KV_QUANT_SCHEME:-uniform}"
QWEN36_KV_GROUP_SIZE="${QWEN36_KV_GROUP_SIZE:-64}"
QWEN36_QUANTIZED_KV_START="${QWEN36_QUANTIZED_KV_START:-0}"
QWEN36_PREFILL_STEP_SIZE="${QWEN36_PREFILL_STEP_SIZE-}"
QWEN36_MAX_TOKENS="${QWEN36_MAX_TOKENS-}"
QWEN36_APC_ENABLED="${QWEN36_APC_ENABLED:-1}"
QWEN36_APC_BLOCK_SIZE="${QWEN36_APC_BLOCK_SIZE:-16}"
QWEN36_APC_NUM_BLOCKS="${QWEN36_APC_NUM_BLOCKS:-2048}"
QWEN36_RUN_DIR="${QWEN36_RUN_DIR:-run}"
QWEN36_LOG="${QWEN36_LOG:-${QWEN36_RUN_DIR}/qwen36-backend.log}"
QWEN36_PID="${QWEN36_PID:-${QWEN36_RUN_DIR}/qwen36-backend.pid}"

if [[ "${QWEN36_RUN_DIR}" != /* ]]; then
  QWEN36_RUN_DIR="${ROOT_DIR}/${QWEN36_RUN_DIR}"
fi
if [[ "${QWEN36_LOG}" != /* ]]; then
  QWEN36_LOG="${ROOT_DIR}/${QWEN36_LOG}"
fi
if [[ "${QWEN36_PID}" != /* ]]; then
  QWEN36_PID="${ROOT_DIR}/${QWEN36_PID}"
fi

export ROOT_DIR
export QWEN36_BACKEND_TYPE QWEN36_LLAMA_SERVER
export QWEN36_PYTHON QWEN36_MODEL QWEN36_RUNTIME_CWD QWEN36_RENCROW_START_SCRIPT QWEN36_DIRECT_START
export QWEN36_USE_MGMT QWEN36_MGMT_BASE
export QWEN36_HOST QWEN36_BACKEND_PORT
export QWEN36_BACKEND_BASE QWEN36_PROXY_BASE
export QWEN36_LLAMA_CONTEXT_SIZE QWEN36_LLAMA_PARALLEL QWEN36_LLAMA_GPU_LAYERS
export QWEN36_LLAMA_FLASH_ATTN QWEN36_LLAMA_CACHE_TYPE_K QWEN36_LLAMA_CACHE_TYPE_V
export QWEN36_LLAMA_CACHE_RAM_MIB QWEN36_LLAMA_CHECKPOINT_MIN_STEP
export QWEN36_LLAMA_CTX_CHECKPOINTS QWEN36_LLAMA_ALIASES
export QWEN36_MAX_KV_SIZE QWEN36_KV_BITS QWEN36_KV_QUANT_SCHEME
export QWEN36_KV_GROUP_SIZE QWEN36_QUANTIZED_KV_START
export QWEN36_PREFILL_STEP_SIZE QWEN36_MAX_TOKENS
export QWEN36_APC_ENABLED QWEN36_APC_BLOCK_SIZE QWEN36_APC_NUM_BLOCKS
export QWEN36_RUN_DIR QWEN36_LOG QWEN36_PID
