#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${QWEN36_ENV_FILE:-${ROOT_DIR}/config/qwen36.env}"

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "env file not found: ${ENV_FILE}" >&2
  exit 1
fi

while IFS='=' read -r key value; do
  [[ -z "${key}" || "${key}" == \#* ]] && continue
  if [[ "${key}" =~ ^[A-Za-z_][A-Za-z0-9_]*$ && -z "${!key+x}" ]]; then
    export "${key}=${value}"
  fi
done <"${ENV_FILE}"

QWEN36_PYTHON="${QWEN36_PYTHON:-/Users/yukimi/RenCrow/RenCrow_LLM/.venv/bin/python3}"
QWEN36_MODEL="${QWEN36_MODEL:-/Users/yukimi/models/Qwen3.6-27B-Uncensored-Heretic-v2-MLX-4bit}"
QWEN36_RUNTIME_CWD="${QWEN36_RUNTIME_CWD:-/Users/yukimi/RenCrow/RenCrow_LLM}"
QWEN36_RENCROW_START_SCRIPT="${QWEN36_RENCROW_START_SCRIPT:-/Users/yukimi/RenCrow/RenCrow_LLM/scripts/start_mlx_vlm_backend.sh}"
QWEN36_DIRECT_START="${QWEN36_DIRECT_START:-0}"
QWEN36_USE_MGMT="${QWEN36_USE_MGMT:-1}"
QWEN36_MGMT_BASE="${QWEN36_MGMT_BASE:-http://127.0.0.1:8079}"
QWEN36_HOST="${QWEN36_HOST:-0.0.0.0}"
QWEN36_BACKEND_PORT="${QWEN36_BACKEND_PORT:-18084}"
QWEN36_BACKEND_BASE="${QWEN36_BACKEND_BASE:-http://127.0.0.1:${QWEN36_BACKEND_PORT}}"
QWEN36_PROXY_BASE="${QWEN36_PROXY_BASE:-http://127.0.0.1:8084}"
QWEN36_MAX_KV_SIZE="${QWEN36_MAX_KV_SIZE-}"
QWEN36_KV_BITS="${QWEN36_KV_BITS-}"
QWEN36_KV_QUANT_SCHEME="${QWEN36_KV_QUANT_SCHEME:-uniform}"
QWEN36_KV_GROUP_SIZE="${QWEN36_KV_GROUP_SIZE:-64}"
QWEN36_QUANTIZED_KV_START="${QWEN36_QUANTIZED_KV_START:-0}"
QWEN36_PREFILL_STEP_SIZE="${QWEN36_PREFILL_STEP_SIZE-}"
QWEN36_MAX_TOKENS="${QWEN36_MAX_TOKENS-}"
QWEN36_RUN_DIR="${QWEN36_RUN_DIR:-run}"
QWEN36_LOG="${QWEN36_LOG:-${QWEN36_RUN_DIR}/qwen36-backend.log}"
QWEN36_PID="${QWEN36_PID:-${QWEN36_RUN_DIR}/qwen36-backend.pid}"

if [[ "${QWEN36_RUN_DIR}" != /* ]]; then
  QWEN36_RUN_DIR="${ROOT_DIR}/${QWEN36_RUN_DIR}"
fi
if [[ "${QWEN36_LOG}" != /* ]]; then
  QWEN36_LOG="${ROOT_DIR}/${QWEN36_LOG}"
fi
if [[ "${QWEN36_PID}" != /* ]]; then
  QWEN36_PID="${ROOT_DIR}/${QWEN36_PID}"
fi

export ROOT_DIR
export QWEN36_PYTHON QWEN36_MODEL QWEN36_RUNTIME_CWD QWEN36_RENCROW_START_SCRIPT QWEN36_DIRECT_START
export QWEN36_USE_MGMT QWEN36_MGMT_BASE
export QWEN36_HOST QWEN36_BACKEND_PORT
export QWEN36_BACKEND_BASE QWEN36_PROXY_BASE
export QWEN36_MAX_KV_SIZE QWEN36_KV_BITS QWEN36_KV_QUANT_SCHEME
export QWEN36_KV_GROUP_SIZE QWEN36_QUANTIZED_KV_START
export QWEN36_PREFILL_STEP_SIZE QWEN36_MAX_TOKENS
export QWEN36_RUN_DIR QWEN36_LOG QWEN36_PID
